server:
  port: 9009
spring:
  application:
    name: tensquare_sms
  rabbitmq:
    host: 192.168.254.128
aliyun:
  sms:
    accessKeyId: LTAI4GCd9tZgQDxfVACVDX3B
    accessKeySecret: qe5PDmywTctgAiNCJCSrkbQBUaddOR
    template_code: SMS_209566033
    sign_name: 自用的短信测试